apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: online-boutique
  name: online-boutique
  namespace: online-boutique

  port:
    targetPort: 80
  to:
    kind: Service
    name: online-boutique
    weight: 100
  wildcardPolicy: None